import { createPuzzle } from './levelUtils';
import type { LevelDefinition, LevelsConfig } from './levelUtils';

export const LEVEL_CONFIGS: LevelsConfig[] = [
  {
    key: 'tutorial',
    label: 'Tutorial',
    levels: [
      {
        id: 'tutorial',
        title: 'Tutorial',
        description: 'Learn how to play with full instructions and guided clues.',
        order: 1,
        isAvailable: true,
        hasInstructions: true,
        puzzle: createPuzzle({
          id: 'tutorial',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tutorial-across',
              direction: 'across',
              word: 'start',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'tutorial-down',
              direction: 'down',
              word: 'gamer',
              startRow: 0,
              startCol: 2,
            },
          ],
          prefilledLetters: { '1-2': 'a' },
        }),
      },
      {
        id: 'tutorial-trail-essay',
        title: 'Tutorial 2',
        description: 'Practice crossing with two guiding letters.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tutorial-trail-essay',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'trail-across',
              direction: 'across',
              word: 'angst',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'essay-down',
              direction: 'down',
              word: 'hinge',
              startRow: 0,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '3-2': 'g',
          },
        }),
      },
      {
        id: 'midline-prism',
        title: 'Tutorial 3',
        description: 'A sweeping glide meets a prismatic rise through the heart column.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'midline-prism',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'midline-prism-across',
              direction: 'across',
              word: 'smile',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'midline-prism-down',
              direction: 'down',
              word: 'flint',
              startRow: 0,
              startCol: 2,
            },
          ],
        }),
      },
    ],
  },
  {
    key: 'two-words',
    label: '2 Words',
    levels: [
      {
        id: 'pivot-point',
        title: 'Pivot Point',
        description: 'Sound and sweets collide one column off center.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'pivot-point',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'pivot-point-across',
              direction: 'across',
              word: 'reign',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'pivot-point-down',
              direction: 'down',
              word: 'argue',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'ember-beacon',
        title: 'Ember Beacon',
        description: 'Heat and light meet near the far column.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ember-beacon',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ember-beacon-across',
              direction: 'across',
              word: 'spike',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'ember-beacon-down',
              direction: 'down',
              word: 'bluer',
              startRow: 0,
              startCol: 4,
            },
          ],
        }),
      },
      {
        id: 'signal-merge',
        title: 'Signal Merge',
        description: 'Guiding beams and steady climbs intersect near the top.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'signal-merge',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'signal-merge-across',
              direction: 'across',
              word: 'suave',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'signal-merge-down',
              direction: 'down',
              word: 'upset',
              startRow: 0,
              startCol: 1,
            },
          ],
        }),
      },
      {
        id: 'ridge-relay',
        title: 'Ridge Relay',
        description: 'A brisk span carries a cresting climb tucked just inside the edge.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ridge-relay',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ridge-relay-across',
              direction: 'across',
              word: 'augur',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'ridge-relay-down',
              direction: 'down',
              word: 'gusty',
              startRow: 0,
              startCol: 1,
            },
          ],
        }),
      },
      {
        id: 'tasty-equine',
        title: 'Tasty equine',
        description: 'Animal running down the green grass.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tasty-equine',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tasty-equine-across',
              direction: 'across',
              word: 'fling',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'tasty-equine-down',
              direction: 'down',
              word: 'fleck',
              startRow: 0,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'lunar-diver',
        title: 'Lunar Diver',
        description: 'A moonlit descent meets aquatic depths at the edge.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'lunar-diver',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'lunar-diver-across',
              direction: 'across',
              word: 'stunt',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'lunar-diver-down',
              direction: 'down',
              word: 'fatty',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-2': 'u',
          },
        }),
      },
    ],
  },
  {
    key: 'three-words',
    label: '3 Words',
    levels: [
      {
        id: 'orbital-triad',
        title: 'Orbital Triad',
        description: 'One bold span supports two vertical ascents from the top row.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'orbital-triad',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'orbital-triad-across',
              direction: 'across',
              word: 'neigh',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'orbital-triad-down-1',
              direction: 'down',
              word: 'early',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'orbital-triad-down-2',
              direction: 'down',
              word: 'geese',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'h-bridge',
        title: 'H Bridge',
        description:
          'Two vertical pillars connected by a horizontal span form the shape of a letter.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'h-bridge',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'h-bridge-down-left',
              direction: 'down',
              word: 'shake',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'h-bridge-down-right',
              direction: 'down',
              word: 'jumbo',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'h-bridge-across',
              direction: 'across',
              word: 'alarm',
              startRow: 2,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'triple-anchor',
        title: 'Triple Anchor',
        description: 'A horizontal beam anchors two descending paths at different points.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'triple-anchor',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'triple-anchor-across',
              direction: 'across',
              word: 'grown',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'triple-anchor-down-1',
              direction: 'down',
              word: 'gassy',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'triple-anchor-down-2',
              direction: 'down',
              word: 'novel',
              startRow: 0,
              startCol: 4,
            },
          ],
        }),
      },
      {
        id: 'tower-cross',
        title: 'Tower Cross',
        description: 'Two vertical towers intersect with a single horizontal span.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tower-cross',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tower-cross-down-1',
              direction: 'down',
              word: 'elfin',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'tower-cross-down-2',
              direction: 'down',
              word: 'freer',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'tower-cross-across',
              direction: 'across',
              word: 'often',
              startRow: 2,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'spread-wings',
        title: 'Spread Wings',
        description: 'A central base supports two upward rising beams like open wings.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'spread-wings',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'spread-wings-across',
              direction: 'across',
              word: 'plead',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'spread-wings-down-1',
              direction: 'down',
              word: 'annul',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'spread-wings-down-2',
              direction: 'down',
              word: 'media',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'fairy-grove',
        title: 'Fairy Grove',
        description: 'Magical beings dance through woodland paths.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'fairy-grove',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'fairy-grove-down-1',
              direction: 'down',
              word: 'paddy',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'fairy-grove-down-2',
              direction: 'down',
              word: 'bison',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'fairy-grove-across',
              direction: 'across',
              word: 'idiom',
              startRow: 3,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '4-1': 'y',
            '4-3': 'm',
          },
        }),
      },
    ],
  },
  {
    key: 'four-words',
    label: '4 Words',
    levels: [
      {
        id: 'luminous-quartet',
        title: 'Luminous Quartet',
        description: 'Twin beams and twin spans outline a glowing square.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'luminous-quartet',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'luminous-quartet-across',
              direction: 'across',
              word: 'bawdy',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'luminous-quartet-down-1',
              direction: 'down',
              word: 'begat',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'luminous-quartet-down-2',
              direction: 'down',
              word: 'young',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'luminous-quartet-across-2',
              direction: 'across',
              word: 'thong',
              startRow: 4,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'apex-peak',
        title: 'Apex Peak',
        description:
          'Two sides converge at a peak, linked by a bar across the middle with a final spine.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'apex-peak',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'apex-peak-down-left',
              direction: 'down',
              word: 'alike',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'apex-peak-down-right',
              direction: 'down',
              word: 'inept',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'apex-peak-across',
              direction: 'across',
              word: 'irate',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'apex-peak-down-center',
              direction: 'down',
              word: 'apart',
              startRow: 0,
              startCol: 2,
            },
          ],
        }),
      },
      {
        id: 'hashtag-grid',
        title: 'Hashtag Grid',
        description:
          'Two vertical pillars intersect with two horizontal spans to form a crosshatch pattern.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'hashtag-grid',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'hashtag-grid-down-left',
              direction: 'down',
              word: 'yeast',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hashtag-grid-down-right',
              direction: 'down',
              word: 'batch',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'hashtag-grid-across-top',
              direction: 'across',
              word: 'enema',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'hashtag-grid-across-bottom',
              direction: 'across',
              word: 'sumac',
              startRow: 3,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'diamond-cross',
        title: 'Diamond Cross',
        description: 'Four words meet in a diamond-like pattern with guided letters.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'diamond-cross',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'diamond-cross-down-1',
              direction: 'down',
              word: 'admit',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'diamond-cross-down-2',
              direction: 'down',
              word: 'sleek',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'diamond-cross-across-1',
              direction: 'across',
              word: 'idyll',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'diamond-cross-across-2',
              direction: 'across',
              word: 'siren',
              startRow: 3,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '3-3': 'e',
            '1-3': 'l',
            '3-1': 'i',
          },
        }),
      },
      {
        id: 'corner-frame',
        title: 'Corner Frame',
        description: 'Four words frame the grid at key intersections forming corners.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'corner-frame',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'corner-frame-down-1',
              direction: 'across',
              word: 'sleet',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'corner-frame-down-2',
              direction: 'across',
              word: 'creek',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'corner-frame-across-1',
              direction: 'across',
              word: 'butch',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'corner-frame-across-2',
              direction: 'down',
              word: 'elect',
              startRow: 0,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '2-2': 'e',
            '0-2': 'e',
          },
        }),
      },
      {
        id: 'ocean-sound',
        title: 'Ocean Sound',
        description: 'Waves meet shores in harmonious crossing.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ocean-sound',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ocean-sound-across-1',
              direction: 'across',
              word: 'yield',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'ocean-sound-across-2',
              direction: 'across',
              word: 'frill',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'ocean-sound-down-1',
              direction: 'down',
              word: 'inter',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'ocean-sound-down-2',
              direction: 'down',
              word: 'legal',
              startRow: 0,
              startCol: 3,
            },
          ],
          prefilledLetters: {
            '4-2': 'r',
            '2-2': 'u',
          },
        }),
      },
    ],
  },
  {
    key: 'five-words',
    label: '5 Words',
    levels: [
      {
        id: 'celestial-column',
        title: 'Celestial Column',
        description: 'Sun and moon spans brace a central beam that pours straight down the middle.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'celestial-column',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'celestial-column-across-1',
              direction: 'across',
              word: 'graft',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'celestial-column-down-left',
              direction: 'down',
              word: 'golem',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'celestial-column-down-right',
              direction: 'down',
              word: 'tenet',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'celestial-column-down-center',
              direction: 'down',
              word: 'arbor',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'celestial-column-across-2',
              direction: 'across',
              word: 'merit',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '4-0': 'm',
            '0-2': 'a',
            '0-4': 't',
          },
        }),
      },
      {
        id: 'inner-span',
        title: 'Inner Span',
        description:
          'Twin pillars burn on the edges while a horizontal core links them across the center.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'inner-span',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'inner-span-across-1',
              direction: 'across',
              word: 'prize',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'inner-span-down-left',
              direction: 'down',
              word: 'pesky',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'inner-span-down-right',
              direction: 'down',
              word: 'epoch',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'inner-span-across-center',
              direction: 'across',
              word: 'salvo',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'inner-span-across-2',
              direction: 'across',
              word: 'youth',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '0-0': 'p',
            '4-0': 'y',
            '0-4': 'e',
          },
        }),
      },
      {
        id: 'vertical-tower',
        title: 'Vertical Tower',
        description: 'Five words form a tall tower with crossing patterns.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'vertical-tower',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'vertical-tower-down-1',
              direction: 'down',
              word: 'leery',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'vertical-tower-down-2',
              direction: 'down',
              word: 'prawn',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'vertical-tower-across-1',
              direction: 'across',
              word: 'anvil',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'vertical-tower-across-2',
              direction: 'across',
              word: 'ruder',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'vertical-tower-across-3',
              direction: 'across',
              word: 'nanny',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '3-0': 'r',
            '6-0': 'n',
            '3-4': 'r',
          },
        }),
      },
      {
        id: 'pentagon-weave',
        title: 'Pentagon Weave',
        description: 'Five interlocking words create a pentagonal pattern across the grid.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'pentagon-weave',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'pentagon-weave-down-1',
              direction: 'down',
              word: 'utter',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'pentagon-weave-down-2',
              direction: 'down',
              word: 'handy',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'pentagon-weave-across-1',
              direction: 'down',
              word: 'realm',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'pentagon-weave-across-2',
              direction: 'across',
              word: 'usher',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'pentagon-weave-across-3',
              direction: 'across',
              word: 'tonga',
              startRow: 2,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '0-2': 'h',
            '0-4': 'r',
            '2-2': 'n',
          },
        }),
      },
      {
        id: 'star-junction',
        title: 'Star Junction',
        description: 'Five beams radiate outward from strategic crossing points.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'star-junction',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'star-junction-across-1',
              direction: 'across',
              word: 'angle',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'star-junction-across-2',
              direction: 'across',
              word: 'worth',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'star-junction-down-1',
              direction: 'across',
              word: 'manor',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'star-junction-down-2',
              direction: 'down',
              word: 'goner',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'star-junction-down-3',
              direction: 'down',
              word: 'earth',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-2': 'n',
            '4-4': 'h',
            '4-2': 'r',
          },
        }),
      },
      {
        id: 'crown-jewel',
        title: 'Crown Jewel',
        description: 'Royal treasures gleam across five perfect alignments.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'crown-jewel',
          grid: { width: 7, height: 5 },
          words: [
            {
              id: 'crown-jewel-across-1',
              direction: 'across',
              word: 'swirl',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crown-jewel-down-1',
              direction: 'down',
              word: 'sheet',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crown-jewel-down-2',
              direction: 'down',
              word: 'radio',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'crown-jewel-across-2',
              direction: 'across',
              word: 'local',
              startRow: 4,
              startCol: 2,
            },
            {
              id: 'crown-jewel-down-3',
              direction: 'down',
              word: 'civil',
              startRow: 0,
              startCol: 6,
            },
          ],
          prefilledLetters: {
            '4-6': 'l',
            '0-0': 's',
            '0-3': 'r',
          },
        }),
      },
    ],
  },
  {
    key: 'six-words',
    label: '6 Words',
    levels: [
      {
        id: 'hexagonal-web',
        title: 'Hexagonal Web',
        description: 'Six interwoven words create a complex web of intersections.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'hexagonal-web',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'hexagonal-web-down-1',
              direction: 'down',
              word: 'hitch',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-down-2',
              direction: 'down',
              word: 'scale',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'hexagonal-web-down-3',
              direction: 'down',
              word: 'dummy',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'hexagonal-web-across-1',
              direction: 'across',
              word: 'hydro',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-across-2',
              direction: 'across',
              word: 'comic',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-across-3',
              direction: 'across',
              word: 'grape',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '3-2': 'm',
            '0-2': 'd',
            '6-4': 'e',
          },
        }),
      },
      {
        id: 'lattice-frame',
        title: 'Lattice Frame',
        description: 'Six words form a lattice pattern with multiple crossings.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'lattice-frame',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'lattice-frame-down-1',
              direction: 'down',
              word: 'hymen',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'lattice-frame-down-2',
              direction: 'down',
              word: 'relic',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'lattice-frame-down-3',
              direction: 'down',
              word: 'miner',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'lattice-frame-across-1',
              direction: 'across',
              word: 'harem',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'lattice-frame-across-2',
              direction: 'across',
              word: 'melon',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'lattice-frame-across-3',
              direction: 'across',
              word: 'nicer',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '4-4': 'r',
            '2-0': 'm',
            '0-2': 'r',
          },
        }),
      },
      {
        id: 'crosshatch-matrix',
        title: 'Crosshatch Matrix',
        description: 'A dense matrix of six words creating multiple intersections.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'crosshatch-matrix',
          grid: { width: 5, height: 8 },
          words: [
            {
              id: 'crosshatch-matrix-across-1',
              direction: 'across',
              word: 'gamma',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-across-2',
              direction: 'down',
              word: 'gayer',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-across-3',
              direction: 'down',
              word: 'amiss',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'crosshatch-matrix-down-1',
              direction: 'across',
              word: 'rebus',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-down-2',
              direction: 'down',
              word: 'abyss',
              startRow: 3,
              startCol: 2,
            },
            {
              id: 'crosshatch-matrix-down-3',
              direction: 'across',
              word: 'musty',
              startRow: 7,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '4-4': 's',
            '4-0': 'r',
            '0-0': 'g',
          },
        }),
      },
      {
        id: 'radial-burst',
        title: 'Radial Burst',
        description: 'Six words radiate from central crossing points like spokes.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'radial-burst',
          grid: { width: 11, height: 5 },
          words: [
            {
              id: 'radial-burst-down-1',
              direction: 'across',
              word: 'chaff',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'radial-burst-down-2',
              direction: 'across',
              word: 'brain',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'radial-burst-across-1',
              direction: 'across',
              word: 'teach',
              startRow: 4,
              startCol: 3,
            },
            {
              id: 'radial-burst-across-2',
              direction: 'across',
              word: 'ingot',
              startRow: 2,
              startCol: 6,
            },
            {
              id: 'radial-burst-across-3',
              direction: 'down',
              word: 'befit',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'radial-burst-down-3',
              direction: 'down',
              word: 'ninth',
              startRow: 0,
              startCol: 7,
            },
          ],
          prefilledLetters: {
            '2-3': 'f',
            '4-3': 't',
            '0-3': 'b',
          },
        }),
      },
      {
        id: 'interlaced-grid',
        title: 'Interlaced Grid',
        description: 'Six words interlace through the grid forming complex crossings.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'interlaced-grid',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'interlaced-grid-across-1',
              direction: 'down',
              word: 'thigh',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'interlaced-grid-across-2',
              direction: 'across',
              word: 'segue',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-across-3',
              direction: 'across',
              word: 'tawny',
              startRow: 7,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-down-1',
              direction: 'down',
              word: 'start',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-down-2',
              direction: 'down',
              word: 'envoy',
              startRow: 3,
              startCol: 4,
            },
            {
              id: 'interlaced-grid-down-3',
              direction: 'down',
              word: 'award',
              startRow: 6,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '3-0': 's',
            '7-0': 't',
            '7-4': 'y',
          },
        }),
      },
      {
        id: 'brain-scope',
        title: 'Brain Scope',
        description: 'Mental pathways intersect through expansive ranges.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'brain-scope',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'brain-scope-down-1',
              direction: 'down',
              word: 'clash',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'brain-scope-across-1',
              direction: 'across',
              word: 'aphid',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'brain-scope-across-2',
              direction: 'across',
              word: 'vinyl',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'brain-scope-down-2',
              direction: 'down',
              word: 'salve',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'brain-scope-down-3',
              direction: 'down',
              word: 'adult',
              startRow: 3,
              startCol: 4,
            },
            {
              id: 'brain-scope-down-4',
              direction: 'down',
              word: 'noise',
              startRow: 6,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '4-2': 'h',
            '4-0': 'a',
            '4-4': 'd',
          },
        }),
      },
    ],
  },
  {
    key: 'seven-words',
    label: '7 Words',
    levels: [
      {
        id: 'stellar-septet',
        title: 'Stellar Septet',
        description: 'Seven stars align across a cosmic grid of intersecting paths.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'stellar-septet',
          grid: { width: 5, height: 9 },
          words: [
            {
              id: 'stellar-septet-across-1',
              direction: 'across',
              word: 'plait',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-2',
              direction: 'across',
              word: 'avian',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-3',
              direction: 'across',
              word: 'laden',
              startRow: 8,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-4',
              direction: 'down',
              word: 'polka',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'stellar-septet-down-1',
              direction: 'down',
              word: 'talon',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'stellar-septet-down-2',
              direction: 'down',
              word: 'viola',
              startRow: 4,
              startCol: 1,
            },
            {
              id: 'stellar-septet-down-3',
              direction: 'down',
              word: 'abode',
              startRow: 4,
              startCol: 3,
            },
          ],
          prefilledLetters: {
            '0-4': 't',
            '4-4': 'n',
            '8-3': 'e',
          },
        }),
      },
      {
        id: 'ladder-climb',
        title: 'Ladder Climb',
        description: 'Seven rungs form a climbing ladder through vertical and horizontal paths.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ladder-climb',
          grid: { width: 5, height: 9 },
          words: [
            {
              id: 'stellar-septet-across-1',
              direction: 'across',
              word: 'cloak',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-2',
              direction: 'across',
              word: 'delve',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-3',
              direction: 'across',
              word: 'credo',
              startRow: 8,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-4',
              direction: 'down',
              word: 'octal',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'stellar-septet-down-1',
              direction: 'across',
              word: 'batty',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'stellar-septet-down-2',
              direction: 'down',
              word: 'enter',
              startRow: 4,
              startCol: 1,
            },
            {
              id: 'stellar-septet-down-3',
              direction: 'down',
              word: 'valid',
              startRow: 4,
              startCol: 3,
            },
          ],
          prefilledLetters: {
            '4-2': 'l',
            '4-1': 'e',
            '4-3': 'v',
          },
        }),
      },
      {
        id: 'spiral-nexus',
        title: 'Spiral Nexus',
        description: 'Seven words spiral around a central nexus point.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'spiral-nexus',
          grid: { width: 11, height: 7 },
          words: [
            {
              id: 'spiral-nexus-across-1',
              direction: 'across',
              word: 'ulcer',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'spiral-nexus-across-2',
              direction: 'across',
              word: 'worry',
              startRow: 2,
              startCol: 3,
            },
            {
              id: 'spiral-nexus-across-3',
              direction: 'across',
              word: 'risky',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'spiral-nexus-down-1',
              direction: 'across',
              word: 'inane',
              startRow: 6,
              startCol: 6,
            },
            {
              id: 'spiral-nexus-down-2',
              direction: 'down',
              word: 'whisk',
              startRow: 2,
              startCol: 3,
            },
            {
              id: 'spiral-nexus-down-3',
              direction: 'down',
              word: 'yearn',
              startRow: 2,
              startCol: 7,
            },
            {
              id: 'spiral-nexus-down-4',
              direction: 'down',
              word: 'carry',
              startRow: 0,
              startCol: 5,
            },
          ],
          prefilledLetters: {
            '2-3': 'w',
            '0-5': 'c',
            '6-7': 'n',
          },
        }),
      },
      {
        id: 'cascade-flow',
        title: 'Cascade Flow',
        description: 'Seven streams cascade down and across the grid in flowing patterns.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cascade-flow',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'cascade-flow-down-1',
              direction: 'down',
              word: 'shale',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cascade-flow-down-2',
              direction: 'down',
              word: 'dopey',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'cascade-flow-down-3',
              direction: 'down',
              word: 'power',
              startRow: 3,
              startCol: 2,
            },
            {
              id: 'cascade-flow-across-1',
              direction: 'down',
              word: 'wreck',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-2',
              direction: 'down',
              word: 'tease',
              startRow: 6,
              startCol: 4,
            },
            {
              id: 'cascade-flow-across-3',
              direction: 'across',
              word: 'ebony',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-4',
              direction: 'across',
              word: 'wheat',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '6-2': 'e',
            '6-4': 't',
            '4-0': 'e',
          },
        }),
      },
      {
        id: 'prism-refraction',
        title: 'Prism Refraction',
        description: 'Seven beams of light refract through a prismatic crossword structure.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'prism-refraction',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'cascade-flow-down-1',
              direction: 'down',
              word: 'poise',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cascade-flow-down-2',
              direction: 'down',
              word: 'scrap',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'cascade-flow-down-3',
              direction: 'down',
              word: 'lilac',
              startRow: 3,
              startCol: 2,
            },
            {
              id: 'cascade-flow-across-1',
              direction: 'down',
              word: 'swill',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-2',
              direction: 'down',
              word: 'hyper',
              startRow: 6,
              startCol: 4,
            },
            {
              id: 'cascade-flow-across-3',
              direction: 'across',
              word: 'salsa',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-4',
              direction: 'across',
              word: 'wacky',
              startRow: 7,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '7-0': 'w',
            '7-2': 'c',
            '3-0': 's',
          },
        }),
      },
      {
        id: 'magic-block',
        title: 'Magic Block',
        description: 'Enchanted words form a mystical structure of seven paths.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'magic-block',
          grid: { width: 9, height: 5 },
          words: [
            {
              id: 'magic-block-across-1',
              direction: 'across',
              word: 'crimp',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'magic-block-across-2',
              direction: 'across',
              word: 'sassy',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'magic-block-across-3',
              direction: 'across',
              word: 'stout',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'magic-block-across-4',
              direction: 'down',
              word: 'chess',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'magic-block-down-1',
              direction: 'down',
              word: 'arose',
              startRow: 0,
              startCol: 6,
            },
            {
              id: 'magic-block-down-2',
              direction: 'down',
              word: 'pushy',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'magic-block-down-3',
              direction: 'down',
              word: 'patio',
              startRow: 0,
              startCol: 8,
            },
          ],
          prefilledLetters: {
            '0-4': 'p',
            '0-0': 'c',
            '2-4': 's',
          },
        }),
      },
    ],
  },
  {
    key: 'eight-words',
    label: '8 Words',
    levels: [
      {
        id: 'octagon-fortress',
        title: 'Octagon Fortress',
        description: 'Eight walls form a fortress of interlocking words across the grid.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'octagon-fortress',
          grid: { width: 7, height: 7 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'genie',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'flunk',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'angel',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'extra',
              startRow: 6,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'guava',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'fugue',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'equal',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'karma',
              startRow: 2,
              startCol: 6,
            },
          ],
          prefilledLetters: {
            '4-0': 'a',
            '2-6': 'k',
            '0-0': 'g',
          },
        }),
      },
      {
        id: 'infinity-loop',
        title: 'Infinity Loop',
        description: 'Eight words loop through the grid creating an infinite pattern.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'infinity-loop',
          grid: { width: 7, height: 7 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'defer',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'cliff',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'debar',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'twang',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'freed',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'cobra',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'flier',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'femur',
              startRow: 2,
              startCol: 6,
            },
          ],
          prefilledLetters: {
            '2-6': 'f',
            '4-2': 'b',
            '4-4': 'r',
          },
        }),
      },
      {
        id: 'cathedral-spires',
        title: 'Cathedral Spires',
        description: 'Eight towering spires rise through a cathedral-like structure.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cathedral-spires',
          grid: { width: 11, height: 11 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'sugar',
              startRow: 3,
              startCol: 3,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'midge',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'saint',
              startRow: 5,
              startCol: 6,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'allot',
              startRow: 7,
              startCol: 3,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'range',
              startRow: 0,
              startCol: 5,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'allow',
              startRow: 6,
              startCol: 5,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'sigma',
              startRow: 3,
              startCol: 3,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'react',
              startRow: 3,
              startCol: 7,
            },
          ],
          prefilledLetters: {
            '5-3': 'g',
            '3-7': 'r',
            '7-5': 'l',
          },
        }),
      },
      {
        id: 'diamond-lattice',
        title: 'Diamond Lattice',
        description: 'Eight interwoven strands create a diamond-patterned lattice.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'diamond-lattice',
          grid: { width: 7, height: 7 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'braid',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'pinch',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'aider',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'plane',
              startRow: 6,
              startCol: 1,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'bloat',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'pedal',
              startRow: 2,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'inner',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'chant',
              startRow: 1,
              startCol: 6,
            },
          ],
          prefilledLetters: {
            '4-2': 'd',
            '0-4': 'i',
            '2-6': 'h',
          },
        }),
      },
      {
        id: 'cosmic-mandala',
        title: 'Cosmic Mandala',
        description: 'Eight radial paths form a cosmic mandala of perfect symmetry.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cosmic-mandala',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'crank',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'abate',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'bland',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'cheat',
              startRow: 10,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'scram',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'skier',
              startRow: 3,
              startCol: 4,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'agora',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'afire',
              startRow: 6,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '4-2': 'a',
            '4-4': 'k',
            '6-0': 'a',
          },
        }),
      },
      {
        id: 'event-stage',
        title: 'Event Stage',
        description: 'Eight acts unfold upon the grand stage of crossings.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'event-stage',
          grid: { width: 5, height: 11 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'rural',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'eagle',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'spoil',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'acorn',
              startRow: 9,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'dryer',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'elder',
              startRow: 3,
              startCol: 4,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'cower',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'gloom',
              startRow: 6,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '4-2': 'r',
            '4-4': 'l',
            '9-2': 'o',
          },
        }),
      },
    ],
  },
];

export const LEVEL_DEFINITIONS: LevelDefinition[] = LEVEL_CONFIGS.flatMap(
  (config) => config.levels,
);

const tutorialDefinition = LEVEL_DEFINITIONS.find((definition) => definition.id === 'tutorial');

if (!tutorialDefinition) {
  throw new Error('Tutorial level definition is required.');
}

export const TUTORIAL_LEVEL = tutorialDefinition.puzzle;
