import { createPuzzle } from './levelUtils';
import type { LevelDefinition, LevelsConfig } from './levelUtils';

export const LEVEL_CONFIGS: LevelsConfig[] = [
  {
    key: 'tutorial',
    label: 'Tutorial',
    levels: [
      {
        id: 'tutorial',
        title: 'Tutorial',
        description: 'Learn how to play with full instructions and guided clues.',
        order: 1,
        isAvailable: true,
        hasInstructions: true,
        puzzle: createPuzzle({
          id: 'tutorial',
          name: 'Tutorial',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tutorial-across',
              direction: 'across',
              word: 'start',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'tutorial-down',
              direction: 'down',
              word: 'gamer',
              startRow: 0,
              startCol: 2,
            },
          ],
          prefilledLetters: { '1-2': 'a' },
        }),
      },
      {
        id: 'tutorial-trail-essay',
        title: 'Tutorial 2',
        description: 'Practice crossing with two guiding letters.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tutorial-trail-essay',
          name: 'Trail & Essay',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'trail-across',
              direction: 'across',
              word: 'trail',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'essay-down',
              direction: 'down',
              word: 'essay',
              startRow: 0,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '3-3': 'i',
            '1-2': 's',
          },
        }),
      },
      {
        id: 'midline-prism',
        title: 'Midline Prism',
        description: 'A sweeping glide meets a prismatic rise through the heart column.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'midline-prism',
          name: 'Midline Prism',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'midline-prism-across',
              direction: 'across',
              word: 'glide',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'midline-prism-down',
              direction: 'down',
              word: 'prism',
              startRow: 0,
              startCol: 2,
            },
          ],
        }),
      },
    ],
  },
  {
    key: 'two-words',
    label: '2 Words',
    levels: [
      {
        id: 'pivot-point',
        title: 'Pivot Point',
        description: 'Sound and sweets collide one column off center.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'pivot-point',
          name: 'Pivot Point',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'pivot-point-across',
              direction: 'across',
              word: 'sound',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'pivot-point-down',
              direction: 'down',
              word: 'candy',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'ember-beacon',
        title: 'Ember Beacon',
        description: 'Heat and light meet near the far column.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ember-beacon',
          name: 'Ember Beacon',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ember-beacon-across',
              direction: 'across',
              word: 'flare',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'ember-beacon-down',
              direction: 'down',
              word: 'ember',
              startRow: 0,
              startCol: 4,
            },
          ],
        }),
      },
      {
        id: 'signal-merge',
        title: 'Signal Merge',
        description: 'Guiding beams and steady climbs intersect near the top.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'signal-merge',
          name: 'Signal Merge',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'signal-merge-across',
              direction: 'across',
              word: 'crane',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'signal-merge-down',
              direction: 'down',
              word: 'rider',
              startRow: 0,
              startCol: 1,
            },
          ],
        }),
      },
      {
        id: 'ridge-relay',
        title: 'Ridge Relay',
        description: 'A brisk span carries a cresting climb tucked just inside the edge.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ridge-relay',
          name: 'Ridge Relay',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ridge-relay-across',
              direction: 'across',
              word: 'brisk',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'ridge-relay-down',
              direction: 'down',
              word: 'crest',
              startRow: 0,
              startCol: 1,
            },
          ],
        }),
      },
      {
        id: 'tasty-equine',
        title: 'Tasty equine',
        description: 'Animal running down the green grass.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tasty-equine',
          name: 'Tasty equine',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tasty-equine-across',
              direction: 'across',
              word: 'zesty',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'tasty-equine-down',
              direction: 'down',
              word: 'zebra',
              startRow: 0,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'lunar-diver',
        title: 'Lunar Diver',
        description: 'A moonlit descent meets aquatic depths at the edge.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'lunar-diver',
          name: 'Lunar Diver',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'lunar-diver-across',
              direction: 'across',
              word: 'lunar',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'lunar-diver-down',
              direction: 'down',
              word: 'diver',
              startRow: 0,
              startCol: 4,
            },
          ],
        }),
      },
    ],
  },
  {
    key: 'three-words',
    label: '3 Words',
    levels: [
      {
        id: 'orbital-triad',
        title: 'Orbital Triad',
        description: 'One bold span supports two vertical ascents from the top row.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'orbital-triad',
          name: 'Orbital Triad',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'orbital-triad-across',
              direction: 'across',
              word: 'solar',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'orbital-triad-down-1',
              direction: 'down',
              word: 'orbit',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'orbital-triad-down-2',
              direction: 'down',
              word: 'arise',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'h-bridge',
        title: 'H Bridge',
        description:
          'Two vertical pillars connected by a horizontal span form the shape of a letter.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'h-bridge',
          name: 'H Bridge',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'h-bridge-down-left',
              direction: 'down',
              word: 'heart',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'h-bridge-down-right',
              direction: 'down',
              word: 'caddy',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'h-bridge-across',
              direction: 'across',
              word: 'award',
              startRow: 2,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'triple-anchor',
        title: 'Triple Anchor',
        description: 'A horizontal beam anchors two descending paths at different points.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'triple-anchor',
          name: 'Triple Anchor',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'triple-anchor-across',
              direction: 'across',
              word: 'tribe',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'triple-anchor-down-1',
              direction: 'down',
              word: 'rainy',
              startRow: 1,
              startCol: 1,
            },
            {
              id: 'triple-anchor-down-2',
              direction: 'down',
              word: 'empty',
              startRow: 1,
              startCol: 4,
            },
          ],
        }),
      },
      {
        id: 'tower-cross',
        title: 'Tower Cross',
        description: 'Two vertical towers intersect with a single horizontal span.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'tower-cross',
          name: 'Tower Cross',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'tower-cross-down-1',
              direction: 'down',
              word: 'mango',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'tower-cross-down-2',
              direction: 'down',
              word: 'orbit',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'tower-cross-across',
              direction: 'across',
              word: 'annoy',
              startRow: 2,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'spread-wings',
        title: 'Spread Wings',
        description: 'A central base supports two upward rising beams like open wings.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'spread-wings',
          name: 'Spread Wings',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'spread-wings-across',
              direction: 'across',
              word: 'watch',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'spread-wings-down-1',
              direction: 'down',
              word: 'swear',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'spread-wings-down-2',
              direction: 'down',
              word: 'batch',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
      {
        id: 'fairy-grove',
        title: 'Fairy Grove',
        description: 'Magical beings dance through woodland paths.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'fairy-grove',
          name: 'Fairy Grove',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'fairy-grove-down-1',
              direction: 'down',
              word: 'fairy',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'fairy-grove-down-2',
              direction: 'down',
              word: 'tryst',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'fairy-grove-across',
              direction: 'across',
              word: 'grove',
              startRow: 3,
              startCol: 0,
            },
          ],
        }),
      },
    ],
  },
  {
    key: 'four-words',
    label: '4 Words',
    levels: [
      {
        id: 'luminous-quartet',
        title: 'Luminous Quartet',
        description: 'Twin beams and twin spans outline a glowing square.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'luminous-quartet',
          name: 'Luminous Quartet',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'luminous-quartet-across',
              direction: 'across',
              word: 'gleam',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'luminous-quartet-down-1',
              direction: 'down',
              word: 'graft',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'luminous-quartet-down-2',
              direction: 'down',
              word: 'mirth',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'luminous-quartet-across-2',
              direction: 'across',
              word: 'torch',
              startRow: 4,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'apex-peak',
        title: 'Apex Peak',
        description:
          'Two sides converge at a peak, linked by a bar across the middle with a final spine.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'apex-peak',
          name: 'Apex Peak',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'apex-peak-down-left',
              direction: 'down',
              word: 'sheet',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'apex-peak-down-right',
              direction: 'down',
              word: 'caret',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'apex-peak-across',
              direction: 'across',
              word: 'enter',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'apex-peak-down-center',
              direction: 'down',
              word: 'after',
              startRow: 0,
              startCol: 2,
            },
          ],
        }),
      },
      {
        id: 'hashtag-grid',
        title: 'Hashtag Grid',
        description:
          'Two vertical pillars intersect with two horizontal spans to form a crosshatch pattern.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'hashtag-grid',
          name: 'Hashtag Grid',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'hashtag-grid-down-left',
              direction: 'down',
              word: 'habit',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hashtag-grid-down-right',
              direction: 'down',
              word: 'facet',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'hashtag-grid-across-top',
              direction: 'across',
              word: 'aroma',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'hashtag-grid-across-bottom',
              direction: 'across',
              word: 'irate',
              startRow: 3,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'diamond-cross',
        title: 'Diamond Cross',
        description: 'Four words meet in a diamond-like pattern with guided letters.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'diamond-cross',
          name: 'Diamond Cross',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'diamond-cross-down-1',
              direction: 'down',
              word: 'dream',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'diamond-cross-down-2',
              direction: 'down',
              word: 'media',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'diamond-cross-across-1',
              direction: 'across',
              word: 'dried',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'diamond-cross-across-2',
              direction: 'across',
              word: 'rapid',
              startRow: 3,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '0-1': 'd',
            '3-3': 'i',
          },
        }),
      },
      {
        id: 'corner-frame',
        title: 'Corner Frame',
        description: 'Four words frame the grid at key intersections forming corners.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'corner-frame',
          name: 'Corner Frame',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'corner-frame-down-1',
              direction: 'down',
              word: 'vigor',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'corner-frame-down-2',
              direction: 'down',
              word: 'realm',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'corner-frame-across-1',
              direction: 'across',
              word: 'aisle',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'corner-frame-across-2',
              direction: 'across',
              word: 'racer',
              startRow: 3,
              startCol: 0,
            },
          ],
        }),
      },
      {
        id: 'ocean-sound',
        title: 'Ocean Sound',
        description: 'Waves meet shores in harmonious crossing.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ocean-sound',
          name: 'Ocean Sound',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'ocean-sound-across-1',
              direction: 'across',
              word: 'ocean',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'ocean-sound-across-2',
              direction: 'across',
              word: 'shore',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'ocean-sound-down-1',
              direction: 'down',
              word: 'coast',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'ocean-sound-down-2',
              direction: 'down',
              word: 'nerve',
              startRow: 0,
              startCol: 3,
            },
          ],
        }),
      },
    ],
  },
  {
    key: 'five-words',
    label: '5 Words',
    levels: [
      {
        id: 'celestial-column',
        title: 'Celestial Column',
        description: 'Sun and moon spans brace a central beam that pours straight down the middle.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'celestial-column',
          name: 'Celestial Column',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'celestial-column-across-1',
              direction: 'across',
              word: 'solar',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'celestial-column-down-left',
              direction: 'down',
              word: 'still',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'celestial-column-down-right',
              direction: 'down',
              word: 'riser',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'celestial-column-down-center',
              direction: 'down',
              word: 'lumen',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'celestial-column-across-2',
              direction: 'across',
              word: 'lunar',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '2-0': 'i',
            '1-2': 'u',
            '3-4': 'e',
          },
        }),
      },
      {
        id: 'inner-span',
        title: 'Inner Span',
        description:
          'Twin pillars burn on the edges while a horizontal core links them across the center.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'inner-span',
          name: 'Inner Span',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'inner-span-across-1',
              direction: 'across',
              word: 'sight',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'inner-span-down-left',
              direction: 'down',
              word: 'shine',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'inner-span-down-right',
              direction: 'down',
              word: 'torch',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'inner-span-across-center',
              direction: 'across',
              word: 'inner',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'inner-span-across-2',
              direction: 'across',
              word: 'earth',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-0': 'h',
            '2-2': 'n',
            '4-4': 'h',
          },
        }),
      },
      {
        id: 'vertical-tower',
        title: 'Vertical Tower',
        description: 'Five words form a tall tower with crossing patterns.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'vertical-tower',
          name: 'Vertical Tower',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'vertical-tower-down-1',
              direction: 'down',
              word: 'trend',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'vertical-tower-down-2',
              direction: 'down',
              word: 'arena',
              startRow: 2,
              startCol: 1,
            },
            {
              id: 'vertical-tower-across-1',
              direction: 'across',
              word: 'trait',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'vertical-tower-across-2',
              direction: 'across',
              word: 'train',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'vertical-tower-across-3',
              direction: 'across',
              word: 'nadir',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '2-1': 'a',
            '6-1': 'a',
          },
        }),
      },
      {
        id: 'pentagon-weave',
        title: 'Pentagon Weave',
        description: 'Five interlocking words create a pentagonal pattern across the grid.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'pentagon-weave',
          name: 'Pentagon Weave',
          grid: { width: 5, height: 6 },
          words: [
            {
              id: 'pentagon-weave-down-1',
              direction: 'down',
              word: 'charm',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'pentagon-weave-down-2',
              direction: 'down',
              word: 'delta',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'pentagon-weave-across-1',
              direction: 'across',
              word: 'chant',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'pentagon-weave-across-2',
              direction: 'across',
              word: 'ranch',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'pentagon-weave-across-3',
              direction: 'across',
              word: 'maple',
              startRow: 5,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-0': 'h',
            '5-4': 'a',
          },
        }),
      },
      {
        id: 'star-junction',
        title: 'Star Junction',
        description: 'Five beams radiate outward from strategic crossing points.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'star-junction',
          name: 'Star Junction',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'star-junction-across-1',
              direction: 'across',
              word: 'steam',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'star-junction-across-2',
              direction: 'across',
              word: 'smart',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'star-junction-down-1',
              direction: 'down',
              word: 'spurt',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'star-junction-down-2',
              direction: 'down',
              word: 'eject',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'star-junction-down-3',
              direction: 'down',
              word: 'month',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '3-0': 'r',
            '2-2': 'e',
          },
        }),
      },
      {
        id: 'crown-jewel',
        title: 'Crown Jewel',
        description: 'Royal treasures gleam across five perfect alignments.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'crown-jewel',
          name: 'Crown Jewel',
          grid: { width: 5, height: 5 },
          words: [
            {
              id: 'crown-jewel-down-1',
              direction: 'down',
              word: 'crown',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crown-jewel-down-2',
              direction: 'down',
              word: 'jewel',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'crown-jewel-across-1',
              direction: 'across',
              word: 'royal',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'crown-jewel-across-2',
              direction: 'across',
              word: 'worth',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'crown-jewel-down-3',
              direction: 'down',
              word: 'owner',
              startRow: 1,
              startCol: 1,
            },
          ],
          prefilledLetters: {
            '2-0': 'w',
          },
        }),
      },
    ],
  },
  {
    key: 'six-words',
    label: '6 Words',
    levels: [
      {
        id: 'hexagonal-web',
        title: 'Hexagonal Web',
        description: 'Six interwoven words create a complex web of intersections.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'hexagonal-web',
          name: 'Hexagonal Web',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'hexagonal-web-down-1',
              direction: 'down',
              word: 'sight',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-down-2',
              direction: 'down',
              word: 'anvil',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'hexagonal-web-down-3',
              direction: 'down',
              word: 'aware',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'hexagonal-web-across-1',
              direction: 'across',
              word: 'snack',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-across-2',
              direction: 'across',
              word: 'heron',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'hexagonal-web-across-3',
              direction: 'across',
              word: 'viral',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-0': 'i',
            '3-4': 'n',
          },
        }),
      },
      {
        id: 'lattice-frame',
        title: 'Lattice Frame',
        description: 'Six words form a lattice pattern with multiple crossings.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'lattice-frame',
          name: 'Lattice Frame',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'lattice-frame-down-1',
              direction: 'down',
              word: 'brand',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'lattice-frame-down-2',
              direction: 'down',
              word: 'ocean',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'lattice-frame-down-3',
              direction: 'down',
              word: 'width',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'lattice-frame-across-1',
              direction: 'across',
              word: 'boost',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'lattice-frame-across-2',
              direction: 'across',
              word: 'angry',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'lattice-frame-across-3',
              direction: 'across',
              word: 'dealt',
              startRow: 4,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '3-0': 'n',
            '4-2': 'a',
          },
        }),
      },
      {
        id: 'crosshatch-matrix',
        title: 'Crosshatch Matrix',
        description: 'A dense matrix of six words creating multiple intersections.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'crosshatch-matrix',
          name: 'Crosshatch Matrix',
          grid: { width: 5, height: 6 },
          words: [
            {
              id: 'crosshatch-matrix-across-1',
              direction: 'across',
              word: 'plant',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-across-2',
              direction: 'across',
              word: 'angel',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-across-3',
              direction: 'across',
              word: 'tulip',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-down-1',
              direction: 'down',
              word: 'paint',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'crosshatch-matrix-down-2',
              direction: 'down',
              word: 'angel',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'crosshatch-matrix-down-3',
              direction: 'down',
              word: 'tulip',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '1-0': 'a',
            '4-2': 'e',
          },
        }),
      },
      {
        id: 'radial-burst',
        title: 'Radial Burst',
        description: 'Six words radiate from central crossing points like spokes.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'radial-burst',
          name: 'Radial Burst',
          grid: { width: 5, height: 6 },
          words: [
            {
              id: 'radial-burst-down-1',
              direction: 'down',
              word: 'frost',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'radial-burst-down-2',
              direction: 'down',
              word: 'eagle',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'radial-burst-across-1',
              direction: 'across',
              word: 'flame',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'radial-burst-across-2',
              direction: 'across',
              word: 'store',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'radial-burst-across-3',
              direction: 'across',
              word: 'total',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'radial-burst-down-3',
              direction: 'down',
              word: 'motel',
              startRow: 1,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '1-0': 'r',
            '3-0': 't',
          },
        }),
      },
      {
        id: 'interlaced-grid',
        title: 'Interlaced Grid',
        description: 'Six words interlace through the grid forming complex crossings.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'interlaced-grid',
          name: 'Interlaced Grid',
          grid: { width: 5, height: 6 },
          words: [
            {
              id: 'interlaced-grid-across-1',
              direction: 'across',
              word: 'sting',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-across-2',
              direction: 'across',
              word: 'modal',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-across-3',
              direction: 'across',
              word: 'later',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-down-1',
              direction: 'down',
              word: 'small',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'interlaced-grid-down-2',
              direction: 'down',
              word: 'idiot',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'interlaced-grid-down-3',
              direction: 'down',
              word: 'later',
              startRow: 1,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-0': 'm',
            '4-4': 'e',
          },
        }),
      },
      {
        id: 'brain-scope',
        title: 'Brain Scope',
        description: 'Mental pathways intersect through expansive ranges.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'brain-scope',
          name: 'Brain Scope',
          grid: { width: 5, height: 6 },
          words: [
            {
              id: 'brain-scope-down-1',
              direction: 'down',
              word: 'brain',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'brain-scope-down-2',
              direction: 'down',
              word: 'scope',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'brain-scope-across-1',
              direction: 'across',
              word: 'range',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'brain-scope-across-2',
              direction: 'across',
              word: 'admit',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'brain-scope-across-3',
              direction: 'across',
              word: 'night',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'brain-scope-down-3',
              direction: 'down',
              word: 'admit',
              startRow: 1,
              startCol: 2,
            },
          ],
          prefilledLetters: {
            '3-0': 'i',
          },
        }),
      },
    ],
  },
  {
    key: 'seven-words',
    label: '7 Words',
    levels: [
      {
        id: 'stellar-septet',
        title: 'Stellar Septet',
        description: 'Seven stars align across a cosmic grid of intersecting paths.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'stellar-septet',
          name: 'Stellar Septet',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'stellar-septet-across-1',
              direction: 'across',
              word: 'match',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-2',
              direction: 'across',
              word: 'field',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-3',
              direction: 'across',
              word: 'oxide',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'stellar-septet-across-4',
              direction: 'across',
              word: 'loyal',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'stellar-septet-down-1',
              direction: 'down',
              word: 'mango',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'stellar-septet-down-2',
              direction: 'down',
              word: 'tidal',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'stellar-septet-down-3',
              direction: 'down',
              word: 'hotel',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '1-0': 'a',
            '3-2': 'a',
            '5-4': 'e',
          },
        }),
      },
      {
        id: 'ladder-climb',
        title: 'Ladder Climb',
        description: 'Seven rungs form a climbing ladder through vertical and horizontal paths.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'ladder-climb',
          name: 'Ladder Climb',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'ladder-climb-down-1',
              direction: 'down',
              word: 'spade',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'ladder-climb-down-2',
              direction: 'down',
              word: 'bench',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'ladder-climb-down-3',
              direction: 'down',
              word: 'ninja',
              startRow: 1,
              startCol: 4,
            },
            {
              id: 'ladder-climb-across-1',
              direction: 'across',
              word: 'saber',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'ladder-climb-across-2',
              direction: 'across',
              word: 'drawn',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'ladder-climb-across-3',
              direction: 'across',
              word: 'delta',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'ladder-climb-across-4',
              direction: 'across',
              word: 'enjoy',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-0': 'p',
            '3-3': 'c',
            '5-4': 'j',
          },
        }),
      },
      {
        id: 'spiral-nexus',
        title: 'Spiral Nexus',
        description: 'Seven words spiral around a central nexus point.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'spiral-nexus',
          name: 'Spiral Nexus',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'spiral-nexus-across-1',
              direction: 'across',
              word: 'salty',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'spiral-nexus-across-2',
              direction: 'across',
              word: 'lingo',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'spiral-nexus-across-3',
              direction: 'across',
              word: 'tempo',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'spiral-nexus-down-1',
              direction: 'down',
              word: 'moist',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'spiral-nexus-down-2',
              direction: 'down',
              word: 'title',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'spiral-nexus-down-3',
              direction: 'down',
              word: 'angst',
              startRow: 1,
              startCol: 1,
            },
            {
              id: 'spiral-nexus-down-4',
              direction: 'down',
              word: 'youth',
              startRow: 1,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-1': 'n',
            '4-0': 'e',
            '6-4': 'h',
          },
        }),
      },
      {
        id: 'cascade-flow',
        title: 'Cascade Flow',
        description: 'Seven streams cascade down and across the grid in flowing patterns.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cascade-flow',
          name: 'Cascade Flow',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'cascade-flow-down-1',
              direction: 'down',
              word: 'grasp',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'cascade-flow-down-2',
              direction: 'down',
              word: 'arrow',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'cascade-flow-down-3',
              direction: 'down',
              word: 'lyric',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'cascade-flow-across-1',
              direction: 'across',
              word: 'agile',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-2',
              direction: 'across',
              word: 'sadly',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-3',
              direction: 'across',
              word: 'lower',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'cascade-flow-across-4',
              direction: 'across',
              word: 'topic',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-1': 'r',
            '3-3': 'o',
            '5-4': 'i',
          },
        }),
      },
      {
        id: 'prism-refraction',
        title: 'Prism Refraction',
        description: 'Seven beams of light refract through a prismatic crossword structure.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'prism-refraction',
          name: 'Prism Refraction',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'prism-refraction-across-1',
              direction: 'across',
              word: 'panel',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'prism-refraction-across-2',
              direction: 'across',
              word: 'lathe',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'prism-refraction-across-3',
              direction: 'across',
              word: 'cider',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'prism-refraction-down-1',
              direction: 'down',
              word: 'alpha',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'prism-refraction-down-2',
              direction: 'down',
              word: 'llama',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'prism-refraction-down-3',
              direction: 'down',
              word: 'needy',
              startRow: 1,
              startCol: 2,
            },
            {
              id: 'prism-refraction-down-4',
              direction: 'down',
              word: 'early',
              startRow: 1,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-0': 'a',
            '4-2': 'e',
            '6-4': 'y',
          },
        }),
      },
      {
        id: 'magic-block',
        title: 'Magic Block',
        description: 'Enchanted words form a mystical structure of seven paths.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'magic-block',
          name: 'Magic Block',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'magic-block-across-1',
              direction: 'across',
              word: 'magic',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'magic-block-across-2',
              direction: 'across',
              word: 'block',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'magic-block-across-3',
              direction: 'across',
              word: 'stick',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'magic-block-across-4',
              direction: 'across',
              word: 'glyph',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'magic-block-down-1',
              direction: 'down',
              word: 'amber',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'magic-block-down-2',
              direction: 'down',
              word: 'glory',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'magic-block-down-3',
              direction: 'down',
              word: 'click',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '1-1': 'm',
            '3-3': 'r',
          },
        }),
      },
    ],
  },
  {
    key: 'eight-words',
    label: '8 Words',
    levels: [
      {
        id: 'octagon-fortress',
        title: 'Octagon Fortress',
        description: 'Eight walls form a fortress of interlocking words across the grid.',
        order: 1,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'octagon-fortress',
          name: 'Octagon Fortress',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'octagon-fortress-across-1',
              direction: 'across',
              word: 'float',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-2',
              direction: 'across',
              word: 'rowdy',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-3',
              direction: 'across',
              word: 'weigh',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-across-4',
              direction: 'across',
              word: 'melon',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-1',
              direction: 'down',
              word: 'flame',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'octagon-fortress-down-2',
              direction: 'down',
              word: 'lower',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'octagon-fortress-down-3',
              direction: 'down',
              word: 'amend',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'octagon-fortress-down-4',
              direction: 'down',
              word: 'thorn',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '1-0': 'l',
            '3-1': 'w',
            '5-2': 'n',
          },
        }),
      },
      {
        id: 'infinity-loop',
        title: 'Infinity Loop',
        description: 'Eight words loop through the grid creating an infinite pattern.',
        order: 2,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'infinity-loop',
          name: 'Infinity Loop',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'infinity-loop-down-1',
              direction: 'down',
              word: 'cyber',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'infinity-loop-down-2',
              direction: 'down',
              word: 'radio',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'infinity-loop-down-3',
              direction: 'down',
              word: 'exert',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'infinity-loop-down-4',
              direction: 'down',
              word: 'mayor',
              startRow: 2,
              startCol: 1,
            },
            {
              id: 'infinity-loop-across-1',
              direction: 'across',
              word: 'creed',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'infinity-loop-across-2',
              direction: 'across',
              word: 'bylaw',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'infinity-loop-across-3',
              direction: 'across',
              word: 'among',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'infinity-loop-across-4',
              direction: 'across',
              word: 'rotor',
              startRow: 6,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '2-0': 'e',
            '4-2': 'i',
            '5-4': 'o',
          },
        }),
      },
      {
        id: 'cathedral-spires',
        title: 'Cathedral Spires',
        description: 'Eight towering spires rise through a cathedral-like structure.',
        order: 3,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cathedral-spires',
          name: 'Cathedral Spires',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'cathedral-spires-across-1',
              direction: 'across',
              word: 'threw',
              startRow: 1,
              startCol: 0,
            },
            {
              id: 'cathedral-spires-across-2',
              direction: 'across',
              word: 'error',
              startRow: 3,
              startCol: 0,
            },
            {
              id: 'cathedral-spires-across-3',
              direction: 'across',
              word: 'refer',
              startRow: 5,
              startCol: 0,
            },
            {
              id: 'cathedral-spires-down-1',
              direction: 'down',
              word: 'their',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cathedral-spires-down-2',
              direction: 'down',
              word: 'harem',
              startRow: 1,
              startCol: 1,
            },
            {
              id: 'cathedral-spires-down-3',
              direction: 'down',
              word: 'erode',
              startRow: 1,
              startCol: 2,
            },
            {
              id: 'cathedral-spires-down-4',
              direction: 'down',
              word: 'wrote',
              startRow: 1,
              startCol: 3,
            },
            {
              id: 'cathedral-spires-down-5',
              direction: 'down',
              word: 'error',
              startRow: 1,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '2-1': 'a',
            '4-2': 'o',
            '6-3': 't',
          },
        }),
      },
      {
        id: 'diamond-lattice',
        title: 'Diamond Lattice',
        description: 'Eight interwoven strands create a diamond-patterned lattice.',
        order: 4,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'diamond-lattice',
          name: 'Diamond Lattice',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'diamond-lattice-down-1',
              direction: 'down',
              word: 'fancy',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'diamond-lattice-down-2',
              direction: 'down',
              word: 'noble',
              startRow: 0,
              startCol: 3,
            },
            {
              id: 'diamond-lattice-down-3',
              direction: 'down',
              word: 'opera',
              startRow: 2,
              startCol: 4,
            },
            {
              id: 'diamond-lattice-across-1',
              direction: 'across',
              word: 'sworn',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'diamond-lattice-across-2',
              direction: 'across',
              word: 'annoy',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'diamond-lattice-across-3',
              direction: 'across',
              word: 'cloud',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'diamond-lattice-across-4',
              direction: 'across',
              word: 'yearn',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'diamond-lattice-down-4',
              direction: 'down',
              word: 'acorn',
              startRow: 2,
              startCol: 0,
            },
          ],
          prefilledLetters: {
            '1-1': 'a',
            '3-3': 'l',
            '5-4': 'r',
          },
        }),
      },
      {
        id: 'cosmic-mandala',
        title: 'Cosmic Mandala',
        description: 'Eight radial paths form a cosmic mandala of perfect symmetry.',
        order: 5,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'cosmic-mandala',
          name: 'Cosmic Mandala',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'cosmic-mandala-across-1',
              direction: 'across',
              word: 'chunk',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cosmic-mandala-across-2',
              direction: 'across',
              word: 'harsh',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'cosmic-mandala-across-3',
              direction: 'across',
              word: 'crazy',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'cosmic-mandala-across-4',
              direction: 'across',
              word: 'knelt',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'cosmic-mandala-down-1',
              direction: 'down',
              word: 'check',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'cosmic-mandala-down-2',
              direction: 'down',
              word: 'harsh',
              startRow: 0,
              startCol: 1,
            },
            {
              id: 'cosmic-mandala-down-3',
              direction: 'down',
              word: 'unzip',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'cosmic-mandala-down-4',
              direction: 'down',
              word: 'kayak',
              startRow: 0,
              startCol: 4,
            },
          ],
          prefilledLetters: {
            '1-0': 'h',
            '3-1': 'r',
            '5-2': 'i',
          },
        }),
      },
      {
        id: 'event-stage',
        title: 'Event Stage',
        description: 'Eight acts unfold upon the grand stage of crossings.',
        order: 6,
        isAvailable: true,
        puzzle: createPuzzle({
          id: 'event-stage',
          name: 'Event Stage',
          grid: { width: 5, height: 7 },
          words: [
            {
              id: 'event-stage-down-1',
              direction: 'down',
              word: 'event',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'event-stage-down-2',
              direction: 'down',
              word: 'nerve',
              startRow: 0,
              startCol: 2,
            },
            {
              id: 'event-stage-down-3',
              direction: 'down',
              word: 'ensue',
              startRow: 0,
              startCol: 4,
            },
            {
              id: 'event-stage-across-1',
              direction: 'across',
              word: 'enter',
              startRow: 0,
              startCol: 0,
            },
            {
              id: 'event-stage-across-2',
              direction: 'across',
              word: 'verse',
              startRow: 2,
              startCol: 0,
            },
            {
              id: 'event-stage-across-3',
              direction: 'across',
              word: 'nerve',
              startRow: 4,
              startCol: 0,
            },
            {
              id: 'event-stage-across-4',
              direction: 'across',
              word: 'stage',
              startRow: 6,
              startCol: 0,
            },
            {
              id: 'event-stage-down-4',
              direction: 'down',
              word: 'revel',
              startRow: 2,
              startCol: 1,
            },
          ],
          prefilledLetters: {
            '1-0': 'v',
            '3-2': 'r',
            '5-4': 'u',
          },
        }),
      },
    ],
  },
];

export const LEVEL_DEFINITIONS: LevelDefinition[] = LEVEL_CONFIGS.flatMap(
  (config) => config.levels,
);

const tutorialDefinition = LEVEL_DEFINITIONS.find((definition) => definition.id === 'tutorial');

if (!tutorialDefinition) {
  throw new Error('Tutorial level definition is required.');
}

export const TUTORIAL_LEVEL = tutorialDefinition.puzzle;
